"""Command-line interface for AntisymmetricJ."""

from __future__ import annotations

import argparse
from pathlib import Path

from antisymmetricj.distribution import weighted_distribution
from antisymmetricj.geometry import f_zy
from antisymmetricj.orientations import (
    generate_zcw,
    load_orientations,
    write_orientations,
)
from antisymmetricj.plotting import plot_fzy_overlay, write_fzy_distribution_table

DEFAULT_DISTRIBUTION_ORIENTATIONS = 28_656


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="antisymmetricj",
        description="Calculate antisymmetric J-coupling f_zy distributions.",
        allow_abbrev=False,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    make_zcw_set = subparsers.add_parser(
        "make_zcw_set",
        usage="antisymmetricj make_zcw_set ORIENTATIONS_OUTFILE [options]",
        help="write a legacy ZCW orientation file",
        allow_abbrev=False,
    )
    make_zcw_set.add_argument(
        "orientations_outfile",
        type=Path,
        metavar="ORIENTATIONS_OUTFILE",
    )
    make_zcw_set.add_argument("--min-orientations", type=int, default=832_039)
    make_zcw_set.set_defaults(func=_cmd_make_zcw_set)

    calc_fzy = subparsers.add_parser(
        "calc_fzy",
        usage=(
            "antisymmetricj calc_fzy [ORIENTATIONS_INFILE] "
            "DISTRIBUTION_OUTFILE [options]"
        ),
        help=(
            "calculate a weighted f_zy or f_zy^2 distribution; pass either "
            "DISTRIBUTION_OUTFILE or ORIENTATIONS_INFILE DISTRIBUTION_OUTFILE"
        ),
        allow_abbrev=False,
    )
    calc_fzy.add_argument(
        "paths",
        nargs="+",
        type=Path,
        metavar="DISTRIBUTION_OUTFILE",
        help=(
            "either DISTRIBUTION_OUTFILE for default in-memory ZCW orientations, "
            "or ORIENTATIONS_INFILE DISTRIBUTION_OUTFILE to read orientations "
            "from a file"
        ),
    )
    calc_fzy.add_argument("--plot_fzy", type=Path)
    calc_fzy.add_argument("--c-yx", type=float, default=1.0)
    calc_fzy.add_argument("--c-zx", type=float, default=1.0)
    calc_fzy.add_argument("--bins", type=int, default=200)
    calc_fzy.add_argument(
        "--min-orientations",
        type=int,
        default=DEFAULT_DISTRIBUTION_ORIENTATIONS,
        help=(
            "minimum ZCW orientations to generate when no orientation file is "
            f"supplied (default: {DEFAULT_DISTRIBUTION_ORIENTATIONS})"
        ),
    )
    calc_fzy.add_argument("--squared", action="store_true")
    calc_fzy.add_argument(
        "--format", choices=("auto", "plain", "simpson"), default="auto"
    )
    calc_fzy.add_argument(
        "--angle-unit",
        choices=("radians", "degrees"),
        default="radians",
    )
    calc_fzy.set_defaults(func=_cmd_calc_fzy)

    return parser


def _cmd_make_zcw_set(args: argparse.Namespace) -> None:
    orientations = generate_zcw(min_orientations=args.min_orientations)
    write_orientations(orientations, args.orientations_outfile)


def _cmd_calc_fzy(args: argparse.Namespace) -> None:
    if len(args.paths) == 1:
        distribution_outfile = args.paths[0]
        orientations = generate_zcw(min_orientations=args.min_orientations)
        orientation_source = f"generated_zcw_min_orientations {args.min_orientations}"
    elif len(args.paths) == 2:
        orientations_infile, distribution_outfile = args.paths
        orientations = load_orientations(
            orientations_infile,
            format=args.format,
            angle_unit=args.angle_unit,
        )
        orientation_source = f"orientations_infile {orientations_infile}"
    else:
        raise SystemExit(
            "calc_fzy expects either DISTRIBUTION_OUTFILE or "
            "ORIENTATIONS_INFILE DISTRIBUTION_OUTFILE"
        )

    values = f_zy(
        orientations.alpha,
        orientations.beta,
        c_yx=args.c_yx,
        c_zx=args.c_zx,
    )
    distribution = weighted_distribution(
        values,
        orientations.weights,
        squared=args.squared,
        bins=args.bins,
    )
    observable = "f_zy^2" if args.squared else "f_zy"
    metadata = [
        "generated by antisymmetricj calc_fzy",
        f"observable {observable}",
        f"c_yx {args.c_yx}",
        f"c_zx {args.c_zx}",
        orientation_source,
        f"orientations {len(orientations)}",
        "normalization fraction_per_bin",
    ]
    write_fzy_distribution_table(
        distribution_outfile,
        distribution,
        metadata=metadata,
    )
    if args.plot_fzy is not None:
        plot_fzy_overlay(
            args.plot_fzy,
            [distribution],
            labels=[f"{observable}, c_yx={args.c_yx:g}, c_zx={args.c_zx:g}"],
            xlabel=f"${observable}$",
        )


if __name__ == "__main__":
    raise SystemExit(main())
