from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from antisymmetricj.cli import build_parser, main


def test_cli_zcw_and_distribution(tmp_path: Path) -> None:
    orientations = tmp_path / "orientations_outfile.txt"
    intensities = tmp_path / "distribution_outfile.txt"
    plot = tmp_path / "plot.jpg"

    assert main(["make_zcw_set", str(orientations), "--min-orientations", "54"]) == 0
    assert orientations.exists()

    assert (
        main(
            [
                "calc_fzy",
                str(orientations),
                str(intensities),
                "--plot_fzy",
                str(plot),
                "--bins",
                "20",
                "--c-yx",
                "1",
                "--c-zx",
                "1",
            ]
        )
        == 0
    )
    assert intensities.stat().st_size > 0
    assert plot.stat().st_size > 0
    with Image.open(plot) as image:
        assert image.size[0] > 0
        assert image.size[1] > 0


def test_cli_distribution_can_generate_default_orientations(tmp_path: Path) -> None:
    intensities = tmp_path / "distribution_outfile.txt"
    plot = tmp_path / "default_orientations.jpg"

    assert (
        main(
            [
                "calc_fzy",
                str(intensities),
                "--plot_fzy",
                str(plot),
                "--bins",
                "20",
                "--c-yx",
                "1",
                "--c-zx",
                "1",
            ]
        )
        == 0
    )

    assert intensities.stat().st_size > 0
    assert plot.stat().st_size > 0
    data = np.loadtxt(intensities)
    assert data.shape == (20, 4)
    np.testing.assert_allclose(np.sum(data[:, 3]), 1.0)
    assert "orientations 28656" in intensities.read_text()


def test_cli_distribution_default_orientation_count_can_be_overridden(
    tmp_path: Path,
) -> None:
    intensities = tmp_path / "distribution_outfile.txt"

    assert (
        main(
            [
                "calc_fzy",
                str(intensities),
                "--min-orientations",
                "54",
            ]
        )
        == 0
    )

    assert "orientations 54" in intensities.read_text()


def test_cli_spectrum_can_generate_default_orientations(tmp_path: Path) -> None:
    spectrum = tmp_path / "spectrum_outfile.txt"
    plot = tmp_path / "spectrum.jpg"

    assert (
        main(
            [
                "calc_spectrum",
                str(spectrum),
                "--plot_spectrum",
                str(plot),
                "--min-orientations",
                "54",
                "--sigma-i-hz",
                "60",
                "--sigma-s-hz",
                "10",
                "--j-iso-hz",
                "50",
                "--j-zy-anti-hz",
                "100",
            ]
        )
        == 0
    )

    assert spectrum.stat().st_size > 0
    assert plot.stat().st_size > 0
    data = np.loadtxt(spectrum)
    assert data.shape == (4096, 4)
    assert "generated by antisymmetricj calc_spectrum" in spectrum.read_text()
    assert "orientations 54" in spectrum.read_text()
    assert "sigma_I_hz 60.0" in spectrum.read_text()
    assert "sigma_S_hz 10.0" in spectrum.read_text()
    assert "J_iso_hz 50.0" in spectrum.read_text()
    assert "J_zy_anti_hz 100.0" in spectrum.read_text()
    assert "fwhm_hz 1.0" in spectrum.read_text()
    assert "spectrum_range_hz -150.0 150.0" in spectrum.read_text()
    with Image.open(plot) as image:
        assert image.size[0] > 0
        assert image.size[1] > 0


def test_cli_spectrum_can_read_orientation_file(tmp_path: Path) -> None:
    orientations = tmp_path / "orientations_outfile.txt"
    spectrum = tmp_path / "spectrum_outfile.txt"

    assert main(["make_zcw_set", str(orientations), "--min-orientations", "54"]) == 0
    assert (
        main(
            [
                "calc_spectrum",
                str(orientations),
                str(spectrum),
                "--bins",
                "64",
                "--sigma-i-hz",
                "60",
                "--sigma-s-hz",
                "10",
                "--j-iso-hz",
                "50",
                "--j-zy-anti-hz",
                "100",
            ]
        )
        == 0
    )

    data = np.loadtxt(spectrum)
    assert data.shape == (64, 4)
    assert f"orientations_infile {orientations}" in spectrum.read_text()


def test_cli_distribution_help_names_distribution_outfile(
    capsys: pytest.CaptureFixture[str],
) -> None:
    parser = build_parser()

    with pytest.raises(SystemExit):
        parser.parse_args(["calc_fzy", "--help"])

    captured = capsys.readouterr()
    assert "DISTRIBUTION_OUTFILE" in captured.out
    assert "ORIENTATIONS_INFILE" in captured.out

    with pytest.raises(SystemExit):
        parser.parse_args(["make_zcw_set", "--help"])

    captured = capsys.readouterr()
    assert "ORIENTATIONS_OUTFILE" in captured.out

    with pytest.raises(SystemExit):
        parser.parse_args(["calc_spectrum", "--help"])

    captured = capsys.readouterr()
    assert "SPECTRUM_OUTFILE" in captured.out
    assert "ORIENTATIONS_INFILE" in captured.out


def test_cli_rejects_plot_abbreviation(tmp_path: Path) -> None:
    parser = build_parser()

    with pytest.raises(SystemExit):
        parser.parse_args(
            [
                "calc_fzy",
                str(tmp_path / "distribution_outfile.txt"),
                "--plot",
                str(tmp_path / "plot.jpg"),
            ]
        )
