"""Reproduce Figure 2(a) and 2(b) from the antisymmetric J-coupling paper.

Run from the repository root with:

    PYTHONPATH=src python examples/reproduce_figure2.py

The script writes text intensity tables and JPEG plots into examples/output/.
It is intentionally kept as an example instead of a built-in CLI command so the
scientific choices remain visible and easy to edit.
"""

from __future__ import annotations

from pathlib import Path

from antisymmetricj.distribution import weighted_distribution
from antisymmetricj.geometry import f_zy
from antisymmetricj.orientations import generate_zcw
from antisymmetricj.plotting import (
    plot_fzy_overlay,
    write_fzy_distribution_table,
    write_fzy_overlay_distribution_table,
)

FIGURE2A_CASES: tuple[tuple[str, float, float], ...] = (
    (r"(i) $c_{yx}=0,\ c_{zx}=0$", 0.0, 0.0),
    (r"(ii) $c_{yx}=1,\ c_{zx}=1$", 1.0, 1.0),
    (r"(iii) $c_{yx}=0,\ c_{zx}=0.8$", 0.0, 0.8),
)

SOLID_COLORS = ("#0072B2", "#D55E00", "#009E73")


def main(
    *,
    output_dir: Path = Path(__file__).parent / "output",
    bins: int = 200,
    min_orientations: int = 832_039,
) -> None:
    """Generate Figure 2(a) and Figure 2(b) reproduction artifacts."""

    orientations = generate_zcw(min_orientations=min_orientations)
    output_dir.mkdir(parents=True, exist_ok=True)

    figure2a_distributions = []
    figure2a_labels = []
    for label, c_yx, c_zx in FIGURE2A_CASES:
        values = f_zy(orientations.alpha, orientations.beta, c_yx=c_yx, c_zx=c_zx)
        figure2a_distributions.append(
            weighted_distribution(values, orientations.weights, bins=bins)
        )
        figure2a_labels.append(label)

    figure2a_metadata = [
        "generated by examples/reproduce_figure2.py",
        "figure 2a",
        f"orientations {len(orientations)}",
        f"bins {bins}",
        "normalization fraction_per_bin",
    ]
    write_fzy_overlay_distribution_table(
        output_dir / "figure2a_intensities.txt",
        figure2a_distributions,
        labels=figure2a_labels,
        metadata=figure2a_metadata,
    )
    plot_fzy_overlay(
        output_dir / "figure2a.jpg",
        figure2a_distributions,
        labels=figure2a_labels,
        xlabel=r"$f_{zy}$",
        title="Figure 2(a) reproduction",
        colors=SOLID_COLORS,
        linestyles=("-", "-", "-"),
    )

    figure2b_values = f_zy(
        orientations.alpha,
        orientations.beta,
        c_yx=1.0,
        c_zx=1.0,
    )
    figure2b_distribution = weighted_distribution(
        figure2b_values,
        orientations.weights,
        squared=True,
        bins=bins,
    )
    figure2b_metadata = [
        "generated by examples/reproduce_figure2.py",
        "figure 2b",
        "observable f_zy^2",
        "c_yx 1",
        "c_zx 1",
        f"orientations {len(orientations)}",
        f"bins {bins}",
        "normalization fraction_per_bin",
    ]
    write_fzy_distribution_table(
        output_dir / "figure2b_intensities.txt",
        figure2b_distribution,
        metadata=figure2b_metadata,
    )
    plot_fzy_overlay(
        output_dir / "figure2b.jpg",
        [figure2b_distribution],
        labels=[r"$c_{yx}=1,\ c_{zx}=1$"],
        xlabel=r"$f_{zy}^{2}$",
        title="Figure 2(b) reproduction",
        colors=(SOLID_COLORS[0],),
        linestyles=("-",),
    )


if __name__ == "__main__":
    main()
